language: node_js
node_js: stable
install:
  - yarn
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  github-url: github.com/notebook-demo
  on:
    branch: master
